apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # External port for the service (exposed externally)
      targetPort: 8088   # The internal port your app listens on inside the container
  type: LoadBalancer