name: Build and Deploy to AKS
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      # Set up Java using Temurin (Adoptium's updated distribution name)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Use JDK 23 (or whichever version you need)
          distribution: 'temurin'
          java-package: 'jdk'
 
      # Build the application using Maven
      - name: Build with Maven
        run: mvn clean install  # Ensure the target/ems-backend-0.0.1-SNAPSHOT.jar file is created
 
      - name: List target directory for verification
        run: ls -l target/  # Verify the JAR file is generated
 
      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: manicontainer.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t manicontainer.azurecr.io/chm80076/backendcode:$IMAGE_TAG .
          docker push manicontainer.azurecr.io/chm80076/backendcode:$IMAGE_TAG
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}
 
      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/your-deployment-name
