name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use v4 to ensure the latest checkout functionality

      # Set up Java using Temurin (Adoptium's updated distribution name)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          java-package: 'jdk'

      # Build the application using Maven
      - name: Build with Maven
        run: mvn clean install

      - name: List target directory for verification
        run: ls -l target/

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: manicontainer.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t manicontainer.azurecr.io/chm80076/backendcode:$IMAGE_TAG .
          docker push manicontainer.azurecr.io/chm80076/backendcode:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}

      # Add a step to list all files for debugging (verify location of deployment.yaml and service.yaml)
      - name: List files in the repository
        run: ls -l  # This will list all files in the current working directory (root of the repository)

      # Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml  # Make sure these files exist in the root of the repo
          kubectl apply -f service.yaml     # Make sure these files exist in the root of the repo
          kubectl rollout status deployment/java-backend-deployment
